---
- name: Install Python and Flask
  apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: yes

- name: Install Flask via pip
  pip:
    name: flask

- name: Copy Flask app
  copy:
    src: app.py
    dest: /home/ubuntu/app.py
    mode: '0755'

- name: Deploy systemd service for Flask
  template:
    src: flaskapp.service.j2
    dest: /etc/systemd/system/flask.service
    mode: '0644'

- name: Reload systemd
  command: systemctl daemon-reload

- name: Enable and start Flask app
  systemd:
    name: flask
    enabled: yes
    state: started
